// <auto-generated />
namespace LivroDigital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AdicionaRelacaoNparNLivroAutores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionaRelacaoNparNLivroAutores));
        
        string IMigrationMetadata.Id
        {
            get { return "202410311529033_AdicionaRelacaoNparN-Livro-Autores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
